//script generated by Design Team of Savant

var path = "/mxep/";;

var ver='3.0.2'
var m1=new Object
m1.name='m1'
m1.fnm='menu_m1'
if(!window.lastm||window.lastm<1)lastm=1
m1.v17=null
m1.v17Timeout=''
var maxZ=1000
m1.v18m
m1.targetFrame
var docLoaded=false
m1.bIncBorder=true
m1.v29=null
m1.v29Str=''
m1.v55=0
m1.scrollStep=10
m1.fadingSteps=8
m1.itemOverDelay=0
m1.transTLO=0
m1.fixSB=1
m1.v21="."
m1.maxlev=3 //1
m1.v22=0
m1.sepH=10 //0
m1.bHlNL=1
m1.showA=1
m1.bVarWidth=0
m1.bShowDel=0
m1.scrDel=0
m1.v23=150 //145
m1.levelOffset=20 //-1
m1.bord=1
m1.vertSpace=3
m1.sep=1
m1.v19=false
m1.bkv=0
m1.rev=0
m1.shs=3 //0
m1.xOff=0
m1.yOff=0
m1.v20=false
m1.cntFrame=""
m1.menuFrame=""
m1.v24=""
m1.mout=true
m1.iconSize=8
m1.closeDelay=500
m1.tlmOrigBg="#F38809"
m1.tlmOrigCol="#000000"
m1.v25=false
m1.v52=false
m1.v60=0
m1.v11=false
m1.v10=0
m1.ppLeftPad=3
m1.v54=0
m1.v01=2
m1.tlmHlBg="#386383"
m1.tlmHlCol="#fff"
m1.borderCol="#ffffff"
m1.menuHorizontal=true
m1.scrollHeight=6	
m1.attr=new Array("11px",false,false,"#000","#93c592","#FFFFFF","Arial","#498D49","#FFFFFF","#508751");
m1mn1=new Array
(
"Zones","",1,"",""
,"TDSP","",1,"",""
,"Load Profile","",1,"",""
,"Calendar","",1,"",""
,"Losses","",1,"",""
)
m1mn1_1=new Array
(
"Congestion Zone",path +"jsp/global/zones/gCongestionZone.jsp",0,"",""
,"Weather Zone",path +"jsp/global/zones/gWeatherZone.jsp",0,"",""
,"Zipcode",path +"jsp/global/zones/gZipCode.jsp",0,"",""
)
m1mn1_2=new Array
(
"TDSP",path +"jsp/global/tdsp/gtdsp.jsp",0,"",""
,"Meter Type",path +"jsp/global/tdsp/gmetertype.jsp",0,"",""
,"Meter Read Cycles",path +"jsp/global/tdsp/gmeterreadcycles.jsp",0,"",""
,"Service Voltage",path +"jsp/global/tdsp/gservicevoltage.jsp",0,"",""
,"TDSP Rate Class",path +"jsp/",1,"",""
)

m1mn1_2_5=new Array
(
"Rate Codes",path +"jsp/global/tdsp/gratecode.jsp",0,"",""
,"Rate Codes Association",path +"jsp/global/tdsp/gRateCodeAssociation.jsp",0,"",""
)

m1mn1_3=new Array
(
"Load Profile",path +"jsp/global/gLoadProfile.jsp",0,"",""
)

m1mn1_4=new Array
(
"Season",path +"jsp/global/calendar/gSeason.jsp",0,"",""
,"Day Type",path +"jsp/global/calendar/gDayType.jsp",0,"",""
)

m1mn1_5=new Array
(
"Loss Factor Code",path +"jsp/global/losses/gLossFactorCode.jsp",0,"",""
)


m1mn2=new Array
(
"TDSP","",1,"",""
,"Deal Lever",path +"jsp/pconfiguration/dealLevers/pcDealLevers.jsp",0,"",""
,"Calendar",path +"jsp/pconfiguration/calendar/pcCalendar.jsp",0,"",""
,"Charges","",1,"",""
,"Pricing","",1,"",""
,"Losses","",1,"",""
,"Contract Template Config.",path +"jsp/pconfiguration/Contract.jsp",0,"",""

)
m1mn2_1=new Array
(
"Meter Read Dates",path +"jsp/pconfiguration/TDSP/pcMeterReads.jsp",0,"",""
)
m1mn2_4=new Array
(
"TDSP Charges",path +"jsp/pconfiguration/charges/pcTDSPCharges.jsp",0,"",""
,"Other Charges",path +"jsp/pconfiguration/charges/pcOtherCharges.jsp",0,"",""
,"Premium",path +"jsp/default.jsp",0,"",""
,"Taxes",path +"jsp/pconfiguration/charges/pcTaxes.jsp",0,"",""
)
m1mn2_5=new Array
(
"Products",path +"jsp/pconfiguration/Pricing/pcProducts.jsp",0,"",""
)
m1mn2_6=new Array
(
"Transmission Loss Factor",path +"jsp/pconfiguration/Losses/pcTLF.jsp",0,"",""
,"Distribution Loss Factor",path +"jsp/pconfiguration/Losses/pcDLF.jsp",0,"",""
)




m1mn3=new Array
(
"Import Forward Curves",path +"jsp/inputs/importforwardcurves.jsp",0,"",""
,"View Inputs","",1,"",""
,"Prospective Customers",path +"jsp/pricing/ProspectiveCustomersRep.jsp",0,"",""
,"Prospective Customers",path +"jsp/pricing/ProspectiveCustomersMngr.jsp",0,"",""
,"Prospective Customers",path +"jsp/pricing/ProspectiveCustomersAnalyst.jsp",0,"",""
,"Schedule",path +"jsp/pricing/schedule.jsp",0,"",""
,"Pricer","",1,"",""
)

m1mn3_2=new Array
(
"Forward Curves",path +"jsp/inputs/vinFulcrumCurves.jsp",0,"",""
,"TEE Natural Gas",path +"jsp/inputs/vinTEENaturalGas.jsp",0,"",""
,"Profile Details",path +"jsp/inputs/viewProfileDetails.jsp",0,"",""
)

m1mn3_7=new Array
(
"Run",path +"jsp/pricerun/run.jsp",0,"",""
,"Run Results",path +"jsp/pricerun/runresult.jsp",0,"",""
,"CPE",path +"jsp/pricerun/proposal.jsp",0,"",""
,"Contract",path +"jsp/pricing/Contracts.jsp",0,"",""
)

m1mn4=new Array
(
"User Type",path +"jsp/security/usertype.jsp",0,"",""
,"User",path +"jsp/security/user.jsp",0,"",""
,"Roles",path +"jsp/security/roles.jsp",0,"",""
)

absPath=""
if(m1.v19&&!m1.v20){
if(window.location.href.lastIndexOf("\\")>window.location.href.lastIndexOf("/")) {sepCh = "\\" ;} else {sepCh = "/" ;}
absPath=window.location.href.substring(0,window.location.href.lastIndexOf(sepCh)+1)}
m1.v61=0
m1.v02=m1.v23
